/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;
import com.itextpdf.text.BaseColor;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Font;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

import tipografias.Fuentes;
 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class Administrador extends javax.swing.JFrame {

    String user, nombre_usuario;
    public static int sesion_usuario;
    
    Fuentes tipoFuente;
    public Administrador() {
        initComponents();
        tipoFuente = new Fuentes();
        user = Login.user;
        sesion_usuario = 1;

        setSize(800, 600);
        setResizable(false);
        setTitle("Administrador - Sesion de " + user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui3.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
             jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));
        
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select nombre_usuario from usuarios where username = '" + user + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
                
                
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel_footer.setFont(tipoFuente.fuente(tipoFuente.BPR, 0, 12));
                jLabel_Nombreusuario.setFont(tipoFuente.fuente(tipoFuente.BPR, 1, 30));
                jLabel_Nombreusuario.setText(nombre_usuario);
                
            }
            
        } catch (Exception e) {
            System.err.println("Error de conexion desde la interfaz de Administrador");
        }
        
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton_AcercaDe = new javax.swing.JButton();
        jLabel_etc = new javax.swing.JLabel();
        jLabel_Nombreusuario = new javax.swing.JLabel();
        jButton_RegistrarUsuario = new javax.swing.JButton();
        jButton_GestionarUsuarios = new javax.swing.JButton();
        jButton_Capturista = new javax.swing.JButton();
        jButton_Tecnico = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jButton_cerrar = new javax.swing.JButton();
        jButton_minimizar = new javax.swing.JButton();
        jButton_about = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        jLabel6.setText("Acerca de");

        jButton_AcercaDe.setBackground(new java.awt.Color(211, 211, 211));
        jButton_AcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon2.png"))); // NOI18N
        jButton_AcercaDe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jButton_AcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_AcercaDe.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_etc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 6, 50, 50));

        jLabel_Nombreusuario.setBackground(new java.awt.Color(76, 76, 76));
        jLabel_Nombreusuario.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel_Nombreusuario.setText("jLabel1");
        getContentPane().add(jLabel_Nombreusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 125, -1, -1));

        jButton_RegistrarUsuario.setBackground(new java.awt.Color(255, 153, 153));
        jButton_RegistrarUsuario.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton_RegistrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin1.png"))); // NOI18N
        jButton_RegistrarUsuario.setText("                     ");
        jButton_RegistrarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 32, 39), 10, true));
        jButton_RegistrarUsuario.setBorderPainted(false);
        jButton_RegistrarUsuario.setContentAreaFilled(false);
        jButton_RegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_RegistrarUsuario.setFocusPainted(false);
        jButton_RegistrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_RegistrarUsuario.setIconTextGap(3);
        jButton_RegistrarUsuario.setName(""); // NOI18N
        jButton_RegistrarUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin1.png"))); // NOI18N
        jButton_RegistrarUsuario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin1-over.png"))); // NOI18N
        jButton_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 260, 84));

        jButton_GestionarUsuarios.setBackground(new java.awt.Color(255, 153, 153));
        jButton_GestionarUsuarios.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton_GestionarUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jButton_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin2.png"))); // NOI18N
        jButton_GestionarUsuarios.setText("                     ");
        jButton_GestionarUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 32, 39), 10, true));
        jButton_GestionarUsuarios.setBorderPainted(false);
        jButton_GestionarUsuarios.setContentAreaFilled(false);
        jButton_GestionarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GestionarUsuarios.setFocusPainted(false);
        jButton_GestionarUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_GestionarUsuarios.setIconTextGap(3);
        jButton_GestionarUsuarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin2.png"))); // NOI18N
        jButton_GestionarUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin2-over.png"))); // NOI18N
        jButton_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, 260, 84));

        jButton_Capturista.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Capturista.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton_Capturista.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Capturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin3.png"))); // NOI18N
        jButton_Capturista.setText("                       ");
        jButton_Capturista.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 32, 39), 10, true));
        jButton_Capturista.setBorderPainted(false);
        jButton_Capturista.setContentAreaFilled(false);
        jButton_Capturista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Capturista.setFocusPainted(false);
        jButton_Capturista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Capturista.setIconTextGap(3);
        jButton_Capturista.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin3.png"))); // NOI18N
        jButton_Capturista.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin3-over.png"))); // NOI18N
        jButton_Capturista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CapturistaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 340, 260, 84));

        jButton_Tecnico.setBackground(new java.awt.Color(255, 153, 153));
        jButton_Tecnico.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton_Tecnico.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin4.png"))); // NOI18N
        jButton_Tecnico.setText("                        ");
        jButton_Tecnico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 32, 39), 10, true));
        jButton_Tecnico.setBorderPainted(false);
        jButton_Tecnico.setContentAreaFilled(false);
        jButton_Tecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Tecnico.setFocusPainted(false);
        jButton_Tecnico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Tecnico.setIconTextGap(3);
        jButton_Tecnico.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin4.png"))); // NOI18N
        jButton_Tecnico.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-admin4-over.png"))); // NOI18N
        jButton_Tecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 260, 84));

        jLabel_footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_footer.setText("Creado por JensFrans © - 2021 ");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 1, -1, 20));

        jButton_minimizar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1, -1, 20));

        jButton_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-about.png"))); // NOI18N
        jButton_about.setBorderPainted(false);
        jButton_about.setContentAreaFilled(false);
        jButton_about.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_about.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-about.png"))); // NOI18N
        jButton_about.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-about-over.png"))); // NOI18N
        jButton_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 30, 30));

        jLabel_Wallpaper.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui3.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarUsuarioActionPerformed
        

        RegistrarUsuarios registrarUsuarios = new RegistrarUsuarios();
        registrarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jButton_RegistrarUsuarioActionPerformed

    private void jButton_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarUsuariosActionPerformed
        
        GestionarUsuarios gestionarUsuarios = new GestionarUsuarios();
        gestionarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarUsuariosActionPerformed

    private void jButton_CapturistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CapturistaActionPerformed
        
        Capturista capturista = new Capturista();
        capturista.setVisible(true);
        
    }//GEN-LAST:event_jButton_CapturistaActionPerformed

    private void jButton_TecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TecnicoActionPerformed
        
        Tecnico tecnico = new Tecnico();
        tecnico.setVisible(true);
        
    }//GEN-LAST:event_jButton_TecnicoActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        FiveCodMoverJFrame.MousePressed(evt);
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
        
    }//GEN-LAST:event_formMouseDragged

    private void jButton_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aboutActionPerformed
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jButton_aboutActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jButton_cerrarActionPerformed

//null
    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

//Minimizar 
    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }

    }//GEN-LAST:event_jButton_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AcercaDe;
    private javax.swing.JButton jButton_Capturista;
    private javax.swing.JButton jButton_GestionarUsuarios;
    private javax.swing.JButton jButton_RegistrarUsuario;
    private javax.swing.JButton jButton_Tecnico;
    private javax.swing.JButton jButton_about;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Nombreusuario;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_etc;
    private javax.swing.JLabel jLabel_footer;
    // End of variables declaration//GEN-END:variables
}
