/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

import tipografias.Fuentes;


 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class Capturista extends javax.swing.JFrame {
    
    String user, nombre_usuario;
    int sesion_usuario;
    

    /**
     * Creates new form Capturista
     */
    Fuentes tipoFuente;
    
    public Capturista() {
        initComponents();
        tipoFuente = new Fuentes();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;
        
        setSize(800, 600);
        setResizable(false);
        setTitle("Coordinador - Sesion de " + user);
        setLocationRelativeTo(null);
        
        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        
        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui_coo.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
             jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel_footer.setFont(tipoFuente.fuente(tipoFuente.BPR, 0, 12));
                jLabel_user.setFont(tipoFuente.fuente(tipoFuente.BPR, 1, 30));
                jLabel_user.setText(nombre_usuario);
                
            }
        } catch (SQLException e) {
            System.out.println("Error al consultar nombre de coordinador");
        }
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_RegistrarCliente = new javax.swing.JButton();
        jButton_GestionarClientes = new javax.swing.JButton();
        jButton_Imprimir = new javax.swing.JButton();
        jButton_PromoverAlumno = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jButton_minimizar = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_RegistrarCliente.setBackground(new java.awt.Color(244, 244, 244));
        jButton_RegistrarCliente.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_RegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord.png"))); // NOI18N
        jButton_RegistrarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jButton_RegistrarCliente.setBorderPainted(false);
        jButton_RegistrarCliente.setContentAreaFilled(false);
        jButton_RegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_RegistrarCliente.setFocusPainted(false);
        jButton_RegistrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_RegistrarCliente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord.png"))); // NOI18N
        jButton_RegistrarCliente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord-over.png"))); // NOI18N
        jButton_RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, 260, 84));

        jButton_GestionarClientes.setBackground(new java.awt.Color(244, 244, 244));
        jButton_GestionarClientes.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_GestionarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord2.png"))); // NOI18N
        jButton_GestionarClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jButton_GestionarClientes.setBorderPainted(false);
        jButton_GestionarClientes.setContentAreaFilled(false);
        jButton_GestionarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GestionarClientes.setFocusPainted(false);
        jButton_GestionarClientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord2.png"))); // NOI18N
        jButton_GestionarClientes.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord2-over.png"))); // NOI18N
        jButton_GestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 230, 260, 84));

        jButton_Imprimir.setBackground(new java.awt.Color(244, 244, 244));
        jButton_Imprimir.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_Imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord3.png"))); // NOI18N
        jButton_Imprimir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        jButton_Imprimir.setBorderPainted(false);
        jButton_Imprimir.setContentAreaFilled(false);
        jButton_Imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Imprimir.setFocusPainted(false);
        jButton_Imprimir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord3.png"))); // NOI18N
        jButton_Imprimir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-coord3-over.png"))); // NOI18N
        jButton_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 260, 84));

        jButton_PromoverAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-promover.png"))); // NOI18N
        jButton_PromoverAlumno.setBorderPainted(false);
        jButton_PromoverAlumno.setContentAreaFilled(false);
        jButton_PromoverAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_PromoverAlumno.setFocusPainted(false);
        jButton_PromoverAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_PromoverAlumno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-promover.png"))); // NOI18N
        jButton_PromoverAlumno.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-promover-over.png"))); // NOI18N
        jButton_PromoverAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PromoverAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_PromoverAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 337, 260, 84));

        jLabel_footer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_footer.setText("Creado por JensFrans © - 2021 ");
        jLabel_footer.setPreferredSize(new java.awt.Dimension(51, 20));
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, 260, -1));

        jLabel_user.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel_user.setText("jLabel1");
        jLabel_user.setPreferredSize(new java.awt.Dimension(51, 20));
        getContentPane().add(jLabel_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 125, 330, 30));

        jButton_minimizar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1, -1, 20));

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 1, -1, 20));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui_coo.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarClienteActionPerformed
        
        RegistrarClientes registrarClientes = new RegistrarClientes();
        registrarClientes.setVisible(true);
        
        
    }//GEN-LAST:event_jButton_RegistrarClienteActionPerformed

    private void jButton_GestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarClientesActionPerformed
        
        GestionarClientes gestionarClientes = new GestionarClientes();
        gestionarClientes.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarClientesActionPerformed

    private void jButton_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirActionPerformed
        
        Document documento = new Document();
        
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Lista_de_Almunos_Registrados.pdf"));
            
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(600, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
            
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("Lista de Alumnos Registrados \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma", 18, Font.BOLD, BaseColor.DARK_GRAY));
            
            documento.open();
            documento.add(header);
            documento.add(parrafo);
            
            PdfPTable tabla = new PdfPTable(6);
            tabla.setWidthPercentage(112f);
            float[] ancho = {2.55f,10.55f,5.50f,13.10f,12.90f,6.90f};//7.60f
            tabla.setWidths(ancho);
            
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("C. I.");
            tabla.addCell("Mención");
            tabla.addCell("E-mail");
            tabla.addCell("Teléfono");
            /*tabla.addCell("Dirección");*/

            
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "select * from alumnoss");
                ResultSet rs = pst.executeQuery();
                
                if (rs.next()) {
                    do {                        
                        
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(8));
                        tabla.addCell(rs.getString(7));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        /*tabla.addCell(rs.getString(5));*/
                        
                        
                    } while (rs.next());
                    documento.add(tabla);
                    
                }
                
            } catch (SQLException e) {
                System.err.println("Error al cargar lista de alumnos.");
            }
            
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte de alumnos creado correctamente.");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al generar pdf...");
        }
        
    }//GEN-LAST:event_jButton_ImprimirActionPerformed

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }

    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        FiveCodMoverJFrame.MousePressed(evt);
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
        
    }//GEN-LAST:event_formMouseDragged

    private void jButton_PromoverAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PromoverAlumnoActionPerformed
        PromoverAlumno promoverAlumno = new PromoverAlumno();
        promoverAlumno.setVisible(true);
    }//GEN-LAST:event_jButton_PromoverAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturista().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GestionarClientes;
    private javax.swing.JButton jButton_Imprimir;
    private javax.swing.JButton jButton_PromoverAlumno;
    private javax.swing.JButton jButton_RegistrarCliente;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_user;
    // End of variables declaration//GEN-END:variables
}
