/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import java.sql.*;
import clases.Conexion;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class EliminarMencion extends javax.swing.JFrame {

    /**
     * Creates new form EliminarMencion
     */
    public EliminarMencion() {
        initComponents();

        setSize(400, 267);
        setTitle("Eliminar mencion de estudio.");
        setLocationRelativeTo(null);
        setResizable(false);

        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui-eliminarmencion.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));

        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_eliminarMencion = new javax.swing.JButton();
        jCheckBox_confirm = new javax.swing.JCheckBox();
        jButton_cerrar = new javax.swing.JButton();
        cmb_Mencion = new javax.swing.JComboBox<>();
        jButton_minimizar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_eliminarMencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-EE.png"))); // NOI18N
        jButton_eliminarMencion.setBorderPainted(false);
        jButton_eliminarMencion.setContentAreaFilled(false);
        jButton_eliminarMencion.setFocusPainted(false);
        jButton_eliminarMencion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_eliminarMencion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-EE.png"))); // NOI18N
        jButton_eliminarMencion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-EE-over.png"))); // NOI18N
        jButton_eliminarMencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarMencionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_eliminarMencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 185, 250, 45));

        jCheckBox_confirm.setText("Confirmar eliminacion");
        getContentPane().add(jCheckBox_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 230, -1, 20));

        jButton_cerrar.setBackground(new java.awt.Color(240, 240, 240));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 4, -1, 20));

        cmb_Mencion.setBackground(new java.awt.Color(240, 240, 240));
        cmb_Mencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica | 1ero | A", "Basica | 1ero | B", "Basica | 1ero | C", "Basica | 2do | A", "Basica | 2do | B", "Basica | 2do | C", "Basica | 3ro | A", "Basica | 3ro | B", "Basica | 3ro | C", "Informatica | 4to |", "Informatica | 5to |", "Informatica | 6to |", "Administracion F. | 4to |", "Administracion F. | 5to |", "Administracion F. | 6to |", "Contabilidad | 4to |", "Contabilidad | 5to |", "Contabilidad | 6to |", "Turismo | 4to |", "Turismo | 5to |", "Turismo | 6to |", "Asistencia Gerencial | 4to |", "Asistencia Gerencial | 5to |", "Asistencia Gerencial | 6to |" }));
        cmb_Mencion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_Mencion.setOpaque(true);
        getContentPane().add(cmb_Mencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 145, 260, 30));

        jButton_minimizar.setBackground(new java.awt.Color(240, 240, 240));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 4, -1, 20));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui-eliminarmencion.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 267));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_eliminarMencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarMencionActionPerformed

        String mencion_delete;

        mencion_delete = cmb_Mencion.getSelectedItem().toString();

        if (jCheckBox_confirm.isSelected()) {

            try {

                Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "delete from materias where id_alumno in(select id_alumno from alumnoss where mencion_alumno = '" + mencion_delete + "')");
                pst2.executeUpdate();
                cn2.close();

                JOptionPane.showMessageDialog(null, "Materias removidas correctamente.");
                this.dispose();

                try {

                    Connection cn = Conexion.conectar();
                    PreparedStatement pst = cn.prepareStatement(
                            "delete from alumnoss where mencion_alumno = '" + mencion_delete + "'");
                    pst.executeUpdate();
                    cn.close();

                    JOptionPane.showMessageDialog(null, "Mencion removida correctamente.");

                } catch (SQLException e) {
                    System.err.println("Error al eliminar la mencion.");
                    JOptionPane.showMessageDialog(null, "Error al eliminar la mencion, contacte al administrador.");
                }

            } catch (SQLException e) {
                System.err.println("Error al eliminar materias de los alumnos.");
                JOptionPane.showMessageDialog(null, "Error al eliminar materias, contacte al administrador.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe de confirmar la eliminacion para continuar.");
        }

    }//GEN-LAST:event_jButton_eliminarMencionActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarMencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarMencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarMencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarMencion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarMencion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Mencion;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_eliminarMencion;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JCheckBox jCheckBox_confirm;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
