/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class GestionarEquipos extends javax.swing.JFrame {

    String user;
    public static int IDequipo_update = 0;
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form GestionarClientes
     */
    public GestionarEquipos() {
        initComponents();
        user = Login.user;

        setSize(680, 440);
        setResizable(false);
        setTitle("Gestion de alumnos - Sesion de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui_imMa.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select id_materia, id_alumno, tipo_materia, calificacion, status from materias");

            ResultSet rs = pst.executeQuery();

            jTable_materias = new JTable(model);
            jScrollPane_materias.setViewportView(jTable_materias);
            
            model.addColumn("ID_Materia");
            model.addColumn("ID_Alumno");
            model.addColumn("Materia");
            model.addColumn("calificacion");
            model.addColumn("Estatus");
            
            jTable_materias.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable_materias.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable_materias.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable_materias.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_materias.getColumnModel().getColumn(4).setPreferredWidth(100);

            while (rs.next()) {

                Object[] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);

                }
                model.addRow(fila);

            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error al llenar la tabla...");
        }

        ObtenerDatosTabla();

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_mostrar = new javax.swing.JButton();
        cmb_estatus = new javax.swing.JComboBox<>();
        jScrollPane_materias = new javax.swing.JScrollPane();
        jTable_materias = new javax.swing.JTable();
        jLabel_footer = new javax.swing.JLabel();
        jButton_minimizar = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_mostrar.setBackground(new java.awt.Color(244, 244, 244));
        jButton_mostrar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-buscar.png"))); // NOI18N
        jButton_mostrar.setBorder(null);
        jButton_mostrar.setBorderPainted(false);
        jButton_mostrar.setContentAreaFilled(false);
        jButton_mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_mostrar.setFocusPainted(false);
        jButton_mostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-buscar.png"))); // NOI18N
        jButton_mostrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-buscar.over.png"))); // NOI18N
        jButton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 55, 35, 35));

        cmb_estatus.setBackground(new java.awt.Color(240, 240, 240));
        cmb_estatus.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "- - - General Basica |1ero|2do|3ro| - - -", "Ingles", "Castellano", "Matematica", "Ciencias", "Educacion fisica", "Geografia-Historia-Ciudadania", "Indroduccion a servicios adtvo, mercadeo y turismo", "Servicios adtvo, mercadeo y turismo I", "Servicios adtvo, mercadeo y turismo II", "Introduccion a la contabilidad", "Fundamentos de la contabilidad I", "Fundamentos de la contabilidad II", "Orientacion", "Fisica", "- - - General Administracion |4to|5to|6to| - - -", "Ofimatica I ", "Ofimatica II ", "Contabilidad", "Nociones generales del derecho", "Teoria general del seguro", "Tecnicas y practicas de administracion y turismo", "Orientacion y convivencia", "Premilitar", "Lesgilacion laboral y mercantil", "Tecnicas y practicas de la mencion I", "Tecnicas y practicas de la mencion II", "Administracion de nomina", "Metodologia de la investigacion y procesos", "Presupuesto empresarial", "Proyecto", "Adiestramiento en servicios administrativos |Pasantias|", "- - - General Contabilidad |4to|5to|6to| - - -", "Tecnicas y practicas de comercio y mercadeo", "Contabilidad general sistemas y procedimientos contables", "Impuestos sobre la renta", "Fundamentos de economia", "Metodologia de la investigacion y procesos estadisticos", "Contabilidad y tecnicas bancarias", "Analisis de estado financiero", "Contabilidad de costo y nociones de auditoria", "Proyecto", "Adiestramiento en servicios contables |Pasantias|", "- - - Generales Informatica |4to|5to|6to| - - -", "Sistemas de informacion", "Introduccion a alguebra", "Mantenimiento y operacion", "Algoritmia y programacion", "Programacion II", "Sistemas operativos y telematica", "Estructura de datos", "Proyecto", "Adiestramiento en servicios tecnologicos |Pasantias|", "- - - General Turismo |4to|5to|6to| - - -", "Ingles practico conversacional I", "Ingles practico conversacional II", "Legislacion y reglamentacion turistica", "Geografia turistica e historia de la cultura", "Promocion y ventas", "Proyecto", "Adiestramiento en servicios turisticos |Pasantias|", "- - - General Asistencia Gerencial |4to|5to|6to| - - -", "Legislacion laboral", "Tecnicas y practicas de la gerencia I", "Tecnicas y practicas de la gerencia II", "Seminario taller", "Banca y finanzas", "Proyecto", "Adiestramiento en servicios de gerencia |Pasantias|" }));
        cmb_estatus.setBorder(null);
        cmb_estatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 62, 150, 23));

        jScrollPane_materias.setBackground(new java.awt.Color(244, 244, 244));
        jScrollPane_materias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 4, true));
        jScrollPane_materias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jTable_materias.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jTable_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_materias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane_materias.setViewportView(jTable_materias);

        getContentPane().add(jScrollPane_materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, 623, 290));

        jLabel_footer.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jLabel_footer.setText("Creado por Squery © - 2021 ");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jButton_minimizar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 1, -1, 20));

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1, -1, 20));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui_imMa.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarActionPerformed

        String seleccion = cmb_estatus.getSelectedItem().toString();
        String query = "";
        
        model.setRowCount(0);
        model.setColumnCount(0);
        
        try {
            Connection cn = Conexion.conectar();
            
            if (seleccion.equalsIgnoreCase("Todos")) {
                query = "select id_materia, id_alumno, tipo_materia, calificacion, status from materias";
            } else {
                query = "select id_materia, id_alumno, tipo_materia, calificacion, status from materias where tipo_materia = '" + seleccion + "'";
            }
            
            PreparedStatement pst = cn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            jTable_materias = new JTable(model);
            jScrollPane_materias.setViewportView(jTable_materias);
            
            model.addColumn("ID_Materia");
            model.addColumn("ID_Alumno");
            model.addColumn("Materia");
            model.addColumn("Calificacion");
            model.addColumn("Estatus");
            
            while (rs.next()) {
                Object [] fila = new Object[5];
                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                
                model.addRow(fila);
            }
            cn.close();
            
            
            
        } catch (SQLException e) {
            System.err.println("Error al llenar la tabla equipos registrados" + e);
        }
        
    ObtenerDatosTabla();
    
    }//GEN-LAST:event_jButton_mostrarActionPerformed

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
      FiveCodMoverJFrame.MousePressed(evt);  
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
      FiveCodMoverJFrame.MouseDraggedFrame(evt, this);   
        
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JButton jButton_mostrar;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JScrollPane jScrollPane_materias;
    private javax.swing.JTable jTable_materias;
    // End of variables declaration//GEN-END:variables

    public void ObtenerDatosTabla() {
        jTable_materias.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_materias.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    IDequipo_update = (int) model.getValueAt(fila_point, columna_point);
                    InformacionEquipoTecnico info = new InformacionEquipoTecnico();
                    info.setVisible(true);

                }
            }

        });
    }

}
