/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class InformacionEquipoTecnico extends javax.swing.JFrame {
    
    int IDequipo = 0, IDcliente_update = 0;
    String user = "", nom_alumno;
    

    /**
     * Creates new form InformacionEquipo
     */
    public InformacionEquipoTecnico() {
        initComponents();
        user = Login.user;
        IDequipo = GestionarEquipos.IDequipo_update;
        IDcliente_update = GestionarClientes.IDcliente_update;
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_alumno from alumnoss where id_alumno = '" + IDcliente_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                nom_alumno = rs.getString("nombre_alumno");
            }
            
        } catch (Exception e) {
            System.err.println("Error al consultar nombre...");
        }
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from materias where id_materia = '" + IDequipo + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                cmb_materia.setSelectedItem(rs.getString("tipo_materia"));
                cmb_status.setSelectedItem(rs.getString("status"));
                
                txt_calificacion.setText(rs.getString("calificacion"));
                txt_maestro.setText(rs.getString("maestro"));
                txt_ultima_Modificacion.setText(rs.getString("ultima_modificacion"));
                
                String dia = "", mes = "", annio = "";
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("annio_ingreso");
                txt_fecha.setText(dia + " del " + mes + " del "+ annio);
                
                jTextPane_observaciones.setText(rs.getString("Observaciones"));
                jTextPane_comentariosTecnico.setText(rs.getString("comentarios_tecnicos"));
                jLabel_revisionTecnicaDe.setText("De " + rs.getString("revision_tecnica_de"));
                
                
                
            }
            
        } catch (Exception e) {
            System.err.println("Error al consultar la informacion de materia"); 
        }
        
        setTitle("Materia registrada con id " + IDequipo + " - Sesion de "+ user);
        setSize(800, 600);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui_imm.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
       
        txt_NombreAlumno.setText(nom_alumno);
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_revisionTecnicaDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_comentariosTecnico = new javax.swing.JTextPane();
        txt_NombreAlumno = new javax.swing.JTextField();
        txt_calificacion = new javax.swing.JTextField();
        txt_maestro = new javax.swing.JTextField();
        txt_ultima_Modificacion = new javax.swing.JTextField();
        txt_fecha = new javax.swing.JTextField();
        cmb_materia = new javax.swing.JComboBox<>();
        cmb_status = new javax.swing.JComboBox<>();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_minimizar = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_revisionTecnicaDe.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel_revisionTecnicaDe.setText("Comentarios:");
        getContentPane().add(jLabel_revisionTecnicaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 283, -1, -1));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 233, 237), 3, true));

        jTextPane_observaciones.setEditable(false);
        jTextPane_observaciones.setBackground(new java.awt.Color(244, 244, 244));
        jTextPane_observaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 244, 244), 3, true));
        jTextPane_observaciones.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jTextPane_observaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 90, 340, 170));

        jTextPane_comentariosTecnico.setBackground(new java.awt.Color(244, 244, 244));
        jTextPane_comentariosTecnico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 244, 244), 3, true));
        jTextPane_comentariosTecnico.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jTextPane_comentariosTecnico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextPane_comentariosTecnico);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 310, 340, 170));

        txt_NombreAlumno.setBackground(new java.awt.Color(240, 240, 240));
        txt_NombreAlumno.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_NombreAlumno.setText(" ");
        txt_NombreAlumno.setBorder(null);
        txt_NombreAlumno.setEnabled(false);
        getContentPane().add(txt_NombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 135, 250, -1));

        txt_calificacion.setBackground(new java.awt.Color(240, 240, 240));
        txt_calificacion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_calificacion.setBorder(null);
        txt_calificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 250, -1));

        txt_maestro.setBackground(new java.awt.Color(240, 240, 240));
        txt_maestro.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_maestro.setBorder(null);
        getContentPane().add(txt_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 250, -1));

        txt_ultima_Modificacion.setBackground(new java.awt.Color(240, 240, 240));
        txt_ultima_Modificacion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_ultima_Modificacion.setBorder(null);
        txt_ultima_Modificacion.setEnabled(false);
        getContentPane().add(txt_ultima_Modificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 535, 250, -1));

        txt_fecha.setBackground(new java.awt.Color(240, 240, 240));
        txt_fecha.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_fecha.setBorder(null);
        txt_fecha.setEnabled(false);
        txt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 250, -1));

        cmb_materia.setBackground(new java.awt.Color(240, 240, 240));
        cmb_materia.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - General Basica |1ero|2do|3ro| - - -", "Ingles", "Castellano", "Matematica", "Ciencias", "Educacion fisica", "Geografia-Historia-Ciudadania", "Indroduccion a servicios adtvo, mercadeo y turismo", "Servicios adtvo, mercadeo y turismo I", "Servicios adtvo, mercadeo y turismo II", "Introduccion a la contabilidad", "Fundamentos de la contabilidad I", "Fundamentos de la contabilidad II", "Orientacion", "Fisica", "- - - General Administracion |4to|5to|6to| - - -", "Ofimatica I ", "Ofimatica II ", "Contabilidad", "Nociones generales del derecho", "Teoria general del seguro", "Tecnicas y practicas de administracion y turismo", "Orientacion y convivencia", "Premilitar", "Lesgilacion laboral y mercantil", "Tecnicas y practicas de la mencion I", "Tecnicas y practicas de la mencion II", "Administracion de nomina", "Metodologia de la investigacion y procesos", "Presupuesto empresarial", "Proyecto", "Adiestramiento en servicios administrativos |Pasantias|", "- - - General Contabilidad |4to|5to|6to| - - -", "Tecnicas y practicas de comercio y mercadeo", "Contabilidad general sistemas y procedimientos contables", "Impuestos sobre la renta", "Fundamentos de economia", "Metodologia de la investigacion y procesos estadisticos", "Contabilidad y tecnicas bancarias", "Analisis de estado financiero", "Contabilidad de costo y nociones de auditoria", "Proyecto", "Adiestramiento en servicios contables |Pasantias|", "- - - Generales Informatica |4to|5to|6to| - - -", "Sistemas de informacion", "Introduccion a alguebra", "Mantenimiento y operacion", "Algoritmia y programacion", "Programacion II", "Sistemas operativos y telematica", "Estructura de datos", "Proyecto", "Adiestramiento en servicios tecnologicos |Pasantias|", "- - - General Turismo |4to|5to|6to| - - -", "Ingles practico conversacional I", "Ingles practico conversacional II", "Legislacion y reglamentacion turistica", "Geografia turistica e historia de la cultura", "Promocion y ventas", "Proyecto", "Adiestramiento en servicios turisticos |Pasantias|", "- - - General Asistencia Gerencial |4to|5to|6to| - - -", "Legislacion laboral", "Tecnicas y practicas de la gerencia I", "Tecnicas y practicas de la gerencia II", "Seminario taller", "Banca y finanzas", "Proyecto", "Adiestramiento en servicios de gerencia |Pasantias|" }));
        cmb_materia.setBorder(null);
        cmb_materia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cmb_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 250, 30));

        cmb_status.setBackground(new java.awt.Color(240, 240, 240));
        cmb_status.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobada", "Reprobada", "No definido", "En recuperacion", "Sin calificar" }));
        cmb_status.setBorder(null);
        cmb_status.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 401, 250, 30));

        jButton_Actualizar.setBackground(new java.awt.Color(244, 244, 244));
        jButton_Actualizar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-imm.png"))); // NOI18N
        jButton_Actualizar.setBorder(null);
        jButton_Actualizar.setBorderPainted(false);
        jButton_Actualizar.setContentAreaFilled(false);
        jButton_Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actualizar.setFocusPainted(false);
        jButton_Actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Actualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-imm.png"))); // NOI18N
        jButton_Actualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-imm-over.png"))); // NOI18N
        jButton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 511, 360, 50));

        jButton_minimizar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 1, -1, 20));

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 1, -1, 20));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui_imm.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarActionPerformed

     String status, comentarios, tecnico;
     
     status = cmb_status.getSelectedItem().toString();
     comentarios = jTextPane_comentariosTecnico.getText();
     tecnico = user;
     
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "update materias set status=?, comentarios_tecnicos=?, revision_tecnica_de=? where id_materia = '" + IDequipo + "'");
            
            pst.setString(1, status);
            pst.setString(2, comentarios);
            pst.setString(3, tecnico);
            
            pst.executeUpdate();
            cn.close();
            
            JOptionPane.showMessageDialog(null, "Actualizacion exitosa.");
            this.dispose();
            
        } catch (SQLException e) {
            System.err.println("Error al actualizar materia");
            JOptionPane.showMessageDialog(null, "¡¡Error al actulizar materia!!, contacte al administrador.");
        }
        
    }//GEN-LAST:event_jButton_ActualizarActionPerformed

    private void txt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaActionPerformed

    private void txt_calificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calificacionActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
      FiveCodMoverJFrame.MousePressed(evt);  
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
      FiveCodMoverJFrame.MouseDraggedFrame(evt, this);   
        
    }//GEN-LAST:event_formMouseDragged

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEquipoTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEquipoTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_revisionTecnicaDe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane_comentariosTecnico;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JTextField txt_NombreAlumno;
    private javax.swing.JTextField txt_calificacion;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_maestro;
    private javax.swing.JTextField txt_ultima_Modificacion;
    // End of variables declaration//GEN-END:variables
public void Limpiar(){
        txt_NombreAlumno.setText("");
        txt_fecha.setText("");
        txt_maestro.setText("");
        txt_calificacion.setText("");
        jTextPane_observaciones.setText("");  
    }

}
