/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import clases.Conexion;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class PromoverBasica extends javax.swing.JFrame {

    /**
     * Creates new form PromoverBasica
     */
    public PromoverBasica() {
        initComponents();

        setSize(400, 400);
        setTitle("Promover alumnos de basica");
        setLocationRelativeTo(null);
        setResizable(false);

        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui-promoverBasic.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));

        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_promover = new javax.swing.JButton();
        jButton_minimizar2 = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        cmb_MencionCursada = new javax.swing.JComboBox<>();
        cmb_MencionPromover = new javax.swing.JComboBox<>();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_promover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-PA.png"))); // NOI18N
        jButton_promover.setBorderPainted(false);
        jButton_promover.setContentAreaFilled(false);
        jButton_promover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_promover.setFocusPainted(false);
        jButton_promover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_promover.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-PA.png"))); // NOI18N
        jButton_promover.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-PA-over.png"))); // NOI18N
        jButton_promover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_promoverActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_promover, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 290, 260, 50));

        jButton_minimizar2.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar2.setBorder(null);
        jButton_minimizar2.setBorderPainted(false);
        jButton_minimizar2.setContentAreaFilled(false);
        jButton_minimizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar2.setFocusPainted(false);
        jButton_minimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizar2MouseClicked(evt);
            }
        });
        jButton_minimizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 20));

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 20));

        cmb_MencionCursada.setBackground(new java.awt.Color(240, 240, 240));
        cmb_MencionCursada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica | 1ero | A", "Basica | 1ero | B", "Basica | 1ero | C", "Basica | 2do | A", "Basica | 2do | B", "Basica | 2do | C", "Basica | 3ro | A", "Basica | 3ro | B", "Basica | 3ro | C", "Informatica | 4to |", "Informatica | 5to |", "Informatica | 6to |", "Administracion F. | 4to |", "Administracion F. | 5to |", "Administracion F. | 6to |", "Contabilidad | 4to |", "Contabilidad | 5to |", "Contabilidad | 6to |", "Turismo | 4to |", "Turismo | 5to |", "Turismo | 6to |", "Asistencia Gerencial | 4to |", "Asistencia Gerencial | 5to |", "Asistencia Gerencial | 6to |" }));
        cmb_MencionCursada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_MencionCursada.setOpaque(true);
        getContentPane().add(cmb_MencionCursada, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 150, 260, 30));

        cmb_MencionPromover.setBackground(new java.awt.Color(240, 240, 240));
        cmb_MencionPromover.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica | 1ero | A", "Basica | 1ero | B", "Basica | 1ero | C", "Basica | 2do | A", "Basica | 2do | B", "Basica | 2do | C", "Basica | 3ro | A", "Basica | 3ro | B", "Basica | 3ro | C", "Informatica | 4to |", "Informatica | 5to |", "Informatica | 6to |", "Administracion F. | 4to |", "Administracion F. | 5to |", "Administracion F. | 6to |", "Contabilidad | 4to |", "Contabilidad | 5to |", "Contabilidad | 6to |", "Turismo | 4to |", "Turismo | 5to |", "Turismo | 6to |", "Asistencia Gerencial | 4to |", "Asistencia Gerencial | 5to |", "Asistencia Gerencial | 6to |" }));
        cmb_MencionPromover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_MencionPromover.setOpaque(true);
        getContentPane().add(cmb_MencionPromover, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 230, 260, 30));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui-promoverBasic.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_promoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_promoverActionPerformed

        int validacion = 0;
        String mencionCursada, mencionPromover;

        mencionCursada = cmb_MencionCursada.getSelectedItem().toString();
        mencionPromover = cmb_MencionPromover.getSelectedItem().toString();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "update alumnoss set mencion_alumno = '" + mencionPromover + "' where mencion_alumno = '" + mencionCursada + "'");
            pst.executeUpdate();
            cn.close();
            
            JOptionPane.showMessageDialog(null, "Promocion realizada correctamente.");
           
            try {

                Connection cn2 = Conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        "delete from materias where id_alumno in(select id_alumno from alumnoss where mencion_alumno = '" + mencionPromover + "')");
                pst2.executeUpdate();
                cn2.close();
                
                JOptionPane.showMessageDialog(null, "Asignaturas de la mencion removidas.");
                this.dispose();
                
            } catch (SQLException e) {
                System.err.println("Error al limpiar tabla materias..");
                JOptionPane.showMessageDialog(null, "Error al limpiar la tabla materias...");
            }

        } catch (SQLException e) {
            System.err.println("Error al realizar la promocion.");
            JOptionPane.showMessageDialog(null, "Error al promocionar el alumno, contacte al administrador.");
        }
        

    }//GEN-LAST:event_jButton_promoverActionPerformed

    private void jButton_minimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizar2MouseClicked

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizar2MouseClicked

    private void jButton_minimizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizar2ActionPerformed

    }//GEN-LAST:event_jButton_minimizar2ActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromoverBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromoverBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromoverBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromoverBasica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromoverBasica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_MencionCursada;
    private javax.swing.JComboBox<String> cmb_MencionPromover;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar2;
    private javax.swing.JButton jButton_promover;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
