/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class RegistrarClientes extends javax.swing.JFrame {
    
    String user;

    /**
     * Creates new form RegistrarClientes
     */
    public RegistrarClientes() {
        initComponents();
        
        user = Login.user;
        
        setTitle("Registrar nuevo alumno - sesion de " + user);
        setSize(400, 650);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui_ra.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
             jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));
        
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_mail = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_ci_alumno = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        cmb_mencion = new javax.swing.JComboBox<>();
        jButton_cerrar = new javax.swing.JButton();
        jButton_minimizar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel4.setText("Telefono:");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel7.setText("Direccion:");

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel8.setText("Mencion:");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jLabel5.setText("Cedula de identidad:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_mail.setBackground(new java.awt.Color(240, 240, 240));
        txt_mail.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_mail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_mail.setBorder(null);
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 204, 250, -1));

        txt_telefono.setBackground(new java.awt.Color(240, 240, 240));
        txt_telefono.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_telefono.setBorder(null);
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 276, 250, -1));

        txt_direccion.setBackground(new java.awt.Color(240, 240, 240));
        txt_direccion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_direccion.setBorder(null);
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 345, 250, -1));

        jButton1.setBackground(new java.awt.Color(244, 244, 244));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru-over.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 535, 270, 50));

        txt_ci_alumno.setBackground(new java.awt.Color(240, 240, 240));
        txt_ci_alumno.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_ci_alumno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_ci_alumno.setBorder(null);
        getContentPane().add(txt_ci_alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 482, 250, -1));

        txt_nombre.setBackground(new java.awt.Color(240, 240, 240));
        txt_nombre.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombre.setBorder(null);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 135, 250, -1));

        cmb_mencion.setBackground(new java.awt.Color(240, 240, 240));
        cmb_mencion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        cmb_mencion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica | 1ero | A", "Basica | 1ero | B", "Basica | 1ero | C", "Basica | 2do | A", "Basica | 2do | B", "Basica | 2do | C", "Basica | 3ro | A", "Basica | 3ro | B", "Basica | 3ro | C", "Informatica | 4to |", "Informatica | 5to |", "Informatica | 6to |", "Administracion F. | 4to |", "Administracion F. | 5to |", "Administracion F. | 6to |", "Contabilidad | 4to |", "Contabilidad | 5to |", "Contabilidad | 6to |", "Turismo | 4to |", "Turismo | 5to |", "Turismo | 6to |", "Asistencia Gerencial | 4to |", "Asistencia Gerencial | 5to |", "Asistencia Gerencial | 6to |" }));
        cmb_mencion.setBorder(null);
        cmb_mencion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_mencion.setOpaque(true);
        getContentPane().add(cmb_mencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 410, 250, 30));

        jButton_cerrar.setBackground(new java.awt.Color(29, 32, 39));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 2, -1, 20));

        jButton_minimizar.setBackground(new java.awt.Color(240, 240, 240));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 2, -1, 20));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui_ra.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int permisos_cmb,validacion = 0;
        String nombre, mail, telefono, direccion, permisos_string = "", ci;
        
        nombre = txt_nombre.getText().trim();
        mail = txt_mail.getText().trim();
        telefono = txt_telefono.getText().trim();
        direccion = txt_direccion.getText().trim();
        permisos_cmb = cmb_mencion.getSelectedIndex() + 1;
        ci = txt_ci_alumno.getText().trim();
        
        if (nombre.equals("")) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }
        if (mail.equals("")) {
            txt_mail.setBackground(Color.red);
            validacion++;
        }
        if (telefono.equals("")) {
            txt_telefono.setBackground(Color.red);
            validacion++;
        }
        if (direccion.equals("")) {
            txt_direccion.setBackground(Color.red);
            validacion++;
        }
        if (permisos_cmb == 1) {
            //Datos CMB mencion
                permisos_string = "Basica | 1ero | A";
        }else if (permisos_cmb == 2) {
                permisos_string = "Basica | 1ero | B";
        }else if (permisos_cmb == 3) {
                permisos_string = "Basica | 1ero | C";
        }else if (permisos_cmb == 4) {
                permisos_string = "Basica | 2do | A";
        }else if (permisos_cmb == 5) {
                permisos_string = "Basica | 2do | B";
        }else if (permisos_cmb == 6) {
                permisos_string = "Basica | 2do | C";
        }else if (permisos_cmb == 7) {
                permisos_string = "Basica | 3ro | A";
        }else if (permisos_cmb == 8) {
                permisos_string = "Basica | 3ro | B";
        }else if (permisos_cmb == 9) {
                permisos_string = "Basica | 3ro | C";
        }else if (permisos_cmb == 10) {
                permisos_string = "Informatica | 4to |";
        }else if (permisos_cmb == 11) {
                permisos_string = "Informatica | 5to |";
        }else if (permisos_cmb == 12) {
                permisos_string = "Informatica | 6to |";
        }else if (permisos_cmb == 13) {
                permisos_string = "Administracion F. | 4to |";
        }else if (permisos_cmb == 14) {
                permisos_string = "Administracion F. | 5to |";
        }else if (permisos_cmb == 15) {
                permisos_string = "Administracion F. | 6to |";
        }else if (permisos_cmb == 16) {
                permisos_string = "Contabilidad | 4to |";
        }else if (permisos_cmb == 17) {
                permisos_string = "Contabilidad | 5to |";
        }else if (permisos_cmb == 18) {
                permisos_string = "Contabilidad | 6to |";
        }else if (permisos_cmb == 19) {
                permisos_string = "Turismo | 4to |";
        }else if (permisos_cmb == 20) {
                permisos_string = "Turismo | 5to |";
        }else if (permisos_cmb == 21) {
                permisos_string = "Turismo | 6to |";
        }else if (permisos_cmb == 22) {
                permisos_string = "Asistencia Gerencial | 4to |";
        }else if (permisos_cmb == 23) {
                permisos_string = "Asistencia Gerencial | 5to |";
        }else if (permisos_cmb == 24) {
                permisos_string = "Asistencia Gerencial | 6to |";
        }
        
        if (ci.equals("")) {
            txt_ci_alumno.setBackground(Color.red);
            validacion++;
        }
        
        if (validacion == 0) {
            
            try {
                
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                    "insert into alumnoss values (?, ?, ?, ?, ?, ?, ?, ?)");
                
                pst.setInt(1, 0);
                pst.setString(2, nombre);
                pst.setString(3, mail);
                pst.setString(4, telefono);
                pst.setString(5, direccion);
                pst.setString(6, user);
                pst.setString(7, permisos_string);
                pst.setString(8, ci);
                
                pst.executeUpdate();
                cn.close();
                
                
                Limpiar();
                
                txt_nombre.setBackground(Color.green);
                txt_mail.setBackground(Color.green);
                txt_telefono.setBackground(Color.green);
                txt_direccion.setBackground(Color.green);
                txt_ci_alumno.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Registro exitoso");
                this.dispose();
                
            } catch (SQLException e) {
                System.out.println("Error en registrar alumno" + e);
                JOptionPane.showMessageDialog(null, "¡¡Error al registrar alumno!!, contactar al administrador.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       
        FiveCodMoverJFrame.MousePressed(evt);
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
        
    }//GEN-LAST:event_formMouseDragged

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_mencion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_ci_alumno;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        txt_nombre.setText("");
        txt_mail.setText("");
        txt_telefono.setText("");
        txt_direccion.setText("");
        txt_ci_alumno.setText("");
        
    }
}
