/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import FiveCodMover.FiveCodMoverJFrame;
import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


 /**
 *
 * @author JensFrans JanfrancoParra@gmail.com-GitHub-JensFrans
 */
public class RegistrarEquipo extends javax.swing.JFrame {
    
    int IDcliente_update = 0;
    String user = "", nom_cliente = "";

    /**
     * Creates new form RegistrarEquipo
     */
    public RegistrarEquipo() {
        initComponents();
        user = Login.user;
        IDcliente_update = GestionarClientes.IDcliente_update;
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_alumno from alumnoss where id_alumno = '" + IDcliente_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                nom_cliente = rs.getString("nombre_alumno");
            }
            
        } catch (SQLException e) {
            System.err.println("Error al consultar el nombre del alumno.");
        }
        
        setTitle("Registrar nueva materia para " + nom_cliente);
        setSize(680, 508);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon(getClass().getResource("/images/gui_rm.png"));
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
        txt_nombreCliente.setText(nom_cliente);
        
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon2.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_cerrar = new javax.swing.JButton();
        jButton_minimizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_calificacion = new javax.swing.JTextField();
        txt_maestro = new javax.swing.JTextField();
        cmb_materia = new javax.swing.JComboBox<>();
        jButton_Registrar = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_cerrar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CCC.png"))); // NOI18N
        jButton_cerrar.setBorder(null);
        jButton_cerrar.setBorderPainted(false);
        jButton_cerrar.setContentAreaFilled(false);
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.setFocusPainted(false);
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 3, -1, 20));

        jButton_minimizar.setBackground(new java.awt.Color(38, 42, 51));
        jButton_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/descargar.png"))); // NOI18N
        jButton_minimizar.setBorder(null);
        jButton_minimizar.setBorderPainted(false);
        jButton_minimizar.setContentAreaFilled(false);
        jButton_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_minimizar.setFocusPainted(false);
        jButton_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_minimizarMouseClicked(evt);
            }
        });
        jButton_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 3, -1, 20));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(230, 233, 237), 5, true));

        jTextPane_observaciones.setBackground(new java.awt.Color(230, 233, 237));
        jTextPane_observaciones.setBorder(null);
        jTextPane_observaciones.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jTextPane_observaciones.setSelectionColor(new java.awt.Color(244, 244, 244));
        jScrollPane1.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 85, 310, 350));

        txt_nombreCliente.setBackground(new java.awt.Color(240, 240, 240));
        txt_nombreCliente.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_nombreCliente.setBorder(null);
        txt_nombreCliente.setEnabled(false);
        getContentPane().add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 250, -1));

        txt_calificacion.setBackground(new java.awt.Color(240, 240, 240));
        txt_calificacion.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_calificacion.setBorder(null);
        txt_calificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 266, 250, -1));

        txt_maestro.setBackground(new java.awt.Color(240, 240, 240));
        txt_maestro.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 16)); // NOI18N
        txt_maestro.setBorder(null);
        getContentPane().add(txt_maestro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 336, 250, -1));

        cmb_materia.setBackground(new java.awt.Color(240, 240, 240));
        cmb_materia.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        cmb_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- - - General Basica |1ero|2do|3ro| - - -", "Ingles", "Castellano", "Matematica", "Ciencias", "Educacion fisica", "Geografia-Historia-Ciudadania", "Indroduccion a servicios adtvo, mercadeo y turismo", "Servicios adtvo, mercadeo y turismo I", "Servicios adtvo, mercadeo y turismo II", "Introduccion a la contabilidad", "Fundamentos de la contabilidad I", "Fundamentos de la contabilidad II", "Orientacion", "Fisica", "- - - General Administracion |4to|5to|6to| - - -", "Ofimatica I ", "Ofimatica II ", "Contabilidad", "Nociones generales del derecho", "Teoria general del seguro", "Tecnicas y practicas de administracion y turismo", "Orientacion y convivencia", "Premilitar", "Lesgilacion laboral y mercantil", "Tecnicas y practicas de la mencion I", "Tecnicas y practicas de la mencion II", "Administracion de nomina", "Metodologia de la investigacion y procesos", "Presupuesto empresarial", "Proyecto", "Adiestramiento en servicios administrativos |Pasantias|", "- - - General Contabilidad |4to|5to|6to| - - -", "Tecnicas y practicas de comercio y mercadeo", "Contabilidad general sistemas y procedimientos contables", "Impuestos sobre la renta", "Fundamentos de economia", "Metodologia de la investigacion y procesos estadisticos", "Contabilidad y tecnicas bancarias", "Analisis de estado financiero", "Contabilidad de costo y nociones de auditoria", "Proyecto", "Adiestramiento en servicios contables |Pasantias|", "- - - Generales Informatica |4to|5to|6to| - - -", "Sistemas de informacion", "Introduccion a alguebra", "Mantenimiento y operacion", "Algoritmia y programacion", "Programacion II", "Sistemas operativos y telematica", "Estructura de datos", "Proyecto", "Adiestramiento en servicios tecnologicos |Pasantias|", "- - - General Turismo |4to|5to|6to| - - -", "Ingles practico conversacional I", "Ingles practico conversacional II", "Legislacion y reglamentacion turistica", "Geografia turistica e historia de la cultura", "Promocion y ventas", "Proyecto", "Adiestramiento en servicios turisticos |Pasantias|", "- - - General Asistencia Gerencial |4to|5to|6to| - - -", "Legislacion laboral", "Tecnicas y practicas de la gerencia I", "Tecnicas y practicas de la gerencia II", "Seminario taller", "Banca y finanzas", "Proyecto", "Adiestramiento en servicios de gerencia |Pasantias|" }));
        cmb_materia.setBorder(null);
        cmb_materia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmb_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_materiaActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 250, 30));

        jButton_Registrar.setBackground(new java.awt.Color(244, 244, 244));
        jButton_Registrar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 11)); // NOI18N
        jButton_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru.png"))); // NOI18N
        jButton_Registrar.setBorder(null);
        jButton_Registrar.setBorderPainted(false);
        jButton_Registrar.setContentAreaFilled(false);
        jButton_Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Registrar.setFocusPainted(false);
        jButton_Registrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru.png"))); // NOI18N
        jButton_Registrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imgBTM/btm-ru-over.png"))); // NOI18N
        jButton_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 388, 270, 50));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gui_rm.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_calificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calificacionActionPerformed

    private void jButton_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarActionPerformed

        int validacion = 0;
        String tipo_materia, calificacion, maestro, dia_ingreso, mes_ingreso, annio_ingreso,
            status, observaciones;
        
        tipo_materia = cmb_materia.getSelectedItem().toString();
        calificacion = txt_calificacion.getText().trim();
        maestro = txt_maestro.getText().trim();
        observaciones = jTextPane_observaciones.getText();
        status = "No definido";
        
        Calendar calendar = Calendar.getInstance();
        
        dia_ingreso = Integer.toString(calendar.get(Calendar.DATE));
        mes_ingreso = Integer.toString(calendar.get(Calendar.MONTH));
      annio_ingreso = Integer.toString(calendar.get(Calendar.YEAR));
        
        if (maestro.equals("")) {
            txt_maestro.setBackground(Color.red);
            validacion++;
        }
        if (calificacion.equals("")) {
            txt_calificacion.setBackground(Color.red);
            validacion++;
        }
        if (observaciones.equals("")) {
            jTextPane_observaciones.setText("Sin observaciones...");
        }
        
        if (validacion == 0) {
            
            try {
                
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                        "insert into materias values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                
                pst.setInt(1, 0);
                pst.setInt(2, IDcliente_update);
                pst.setString(3, tipo_materia);
                pst.setString(4, calificacion);
                pst.setString(5, maestro);
                pst.setString(6, "");
                pst.setString(7, dia_ingreso);
                pst.setString(8, mes_ingreso);
                pst.setString(9, annio_ingreso);
                pst.setString(10, observaciones);
                pst.setString(11, status);
                pst.setString(12, user);
                pst.setString(13, "");
                pst.setString(14, "");
                
                pst.executeUpdate();
                cn.close();
                
                txt_calificacion.setBackground(Color.green);
                txt_maestro.setBackground(Color.green);
                txt_nombreCliente.setBackground(Color.green);
                
                JOptionPane.showMessageDialog(null, "Registro exitoso.");
                this.dispose();
                
                
                
            } catch (SQLException e) {
                System.err.println("Error al registrar materia" + e);
                JOptionPane.showMessageDialog(null, "¡¡Error al registrar materia!!, contacte al administrador.");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos...");
        }
        
    }//GEN-LAST:event_jButton_RegistrarActionPerformed

    private void cmb_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_materiaActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_minimizarMouseClicked

        if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1) {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_jButton_minimizarMouseClicked

    private void jButton_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minimizarActionPerformed

    }//GEN-LAST:event_jButton_minimizarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
        FiveCodMoverJFrame.MousePressed(evt);
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
        
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_materia;
    private javax.swing.JButton jButton_Registrar;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_minimizar;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_observaciones;
    private javax.swing.JTextField txt_calificacion;
    private javax.swing.JTextField txt_maestro;
    private javax.swing.JTextField txt_nombreCliente;
    // End of variables declaration//GEN-END:variables
}
